### ISSUE TITLE
Reported issues with the original skin  

### ISSUE THREAD

**Issue by s0rcee** [ReSupport-MediaWiki/mediawiki-skins-Material#2]
https://phabricator.wikimedia.org/T271175, https://phabricator.wikimedia.org/T271176 and https://phabricator.wikimedia.org/T155458

**Comment by bugsquashing** [comment]
Yeah, the original devs seems to have dropped support of this, and stopped updating it, so security issues are prone to happen.

**Comment by s0rcee** [comment]
Hm, yeah, that’s the issue. This skin can and most likely will get a “Backdoor Surprise” if you will.

**Comment by bugsquashing** [comment]
I’ll try to patch some of these issues.

**Comment by bugsquashing** [comment]
Opening a Phabricator task on gitpull

**Comment by bugsquashing** [comment]
Dealt with sidebard

**Comment by bugsquashing** [comment]
Done!
